repos:
  - repo: local
    hooks:
      - id: black
        language: python
        name: black
        pass_filenames: false
        language_version: python3.9
        entry: poetry run black custard examples

  # - repo: local
  #   hooks:
  #     - id: ruff
  #       language: python
  #       name: ruff
  #       pass_filenames: false
  #       language_version: python3.9
  #       entry: poetry run ruff --fix --exit-non-zero-on-fix --show-fixes custard examples

  # - repo: local
  #   hooks:
  #     - id: mypy
  #       language: python
  #       name: mypy
  #       pass_filenames: false
  #       entry: poetry run mypy custard examples --show-error-codes
