site_name: custard
site_description: 🍬A set of tools that keep Python sweet.
site_url: https://www.python-custard.org/

theme:
    name: 'material'

repo_name: kamalyes/custard
repo_url: https://github.com/kamalyes/custard
edit_uri: ""

nav:
    - 介绍: 'index.md'

markdown_extensions:
  - admonition
  - codehilite:
      css_class: highlight

extra:
  search:
    language: 'zh'

extra_css:
    - css/custom.css

extra_javascript:
  - 'js/chat.js'
  - 'js/sidecar-1.5.0.js'